version: '3'

networks:
  dev:

services:

  #######################  mariadb  ########################
  mysql:
    container_name: mariadb-server
    image: yobasystems/alpine-mariadb:10.5.11
    environment:
      MYSQL_ROOT_PASSWORD: mtQ8chN2
      MYSQL_DATABASE: bridgx
      MYSQL_USER: gf
      MYSQL_PASSWORD: db@galaxy-future.com
    ports:
      - 3306:3306
    volumes:
      - ./init/mysql:/docker-entrypoint-initdb.d/
    restart: always

  #######################  etcd  ########################
  etcd:
    container_name: etcd-server
    image: bitnami/etcd:3
    restart: always
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - 2379:2379
      - 2380:2380

  #######################  bridgx 1.0  ########################
  app:
    container_name: gf-bridgx-api
    build:
      context: .
      dockerfile: ./API.Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - mysql
      - etcd

  scheduler:
    container_name: gf-bridgx-scheduler
    build:
      context: .
      dockerfile: ./SCHEDULER.Dockerfile
    depends_on:
      - mysql
      - etcd